/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class FacturaDividida extends javax.swing.JFrame {

     int numeroActual;
     int numeroLimite;
    /**
     * Creates new form FacturaDividida
     */
    public FacturaDividida(int numeroAct,int numeroLim) {
        initComponents();
        this.setSize(515, 740);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        hora();
        numeroActual=numeroAct;
        numeroLimite=numeroLim;
        txtNumFactDividida.setText(String.valueOf(numeroActual));
    }

    private FacturaDividida() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void hora (){
        Calendar calendario = new GregorianCalendar();
        int hora, minutos, segundos;
        hora =calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);
        System.out.println(hora + ":" + minutos + ":" + segundos);
        txtHora.setText(hora + ":" + minutos + ":" + segundos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDFACT = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboDia = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comboAnio = new javax.swing.JComboBox<>();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumFactDividida = new javax.swing.JTextField();
        btnAgregarProd = new javax.swing.JButton();
        panelFacturalTotal = new javax.swing.JScrollPane();
        tablaFacturaIndividual = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelFacturaIndividual = new javax.swing.JScrollPane();
        tablaFacturaTotal = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fact.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 250, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID Factura :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 80, 50);

        txtIDFACT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIDFACT.setEnabled(false);
        getContentPane().add(txtIDFACT);
        txtIDFACT.setBounds(430, 10, 70, 30);

        txtCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtCedula);
        txtCedula.setBounds(250, 80, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Cedula:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 70, 70, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 130, 70, 50);

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(250, 110, 170, 30);

        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtApellido);
        txtApellido.setBounds(250, 140, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fecha:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 180, 50, 40);

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(comboDia);
        comboDia.setBounds(250, 190, 70, 30);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(comboMes);
        comboMes.setBounds(330, 190, 70, 30);

        comboAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anio", "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(comboAnio);
        comboAnio.setBounds(410, 190, 70, 30);

        txtHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHora.setEnabled(false);
        getContentPane().add(txtHora);
        txtHora.setBounds(250, 230, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Hora:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 220, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cajaRegistradora.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 120, 110);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton.PNG"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonSelect.PNG"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(70, 650, 170, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton.PNG"))); // NOI18N
        jButton2.setText("Siguiente Facturar");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonSelect.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 650, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 100, 70, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Numero de factura dividida:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 30, 180, 50);

        txtNumFactDividida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNumFactDividida.setEnabled(false);
        getContentPane().add(txtNumFactDividida);
        txtNumFactDividida.setBounds(430, 40, 70, 30);

        btnAgregarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/abajo.png"))); // NOI18N
        btnAgregarProd.setText("Agregar");
        btnAgregarProd.setContentAreaFilled(false);
        btnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProd.setFocusCycleRoot(true);
        btnAgregarProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarProd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/abajo2.png"))); // NOI18N
        btnAgregarProd.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProd);
        btnAgregarProd.setBounds(360, 440, 90, 50);

        tablaFacturaIndividual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Costo"
            }
        ));
        panelFacturalTotal.setViewportView(tablaFacturaIndividual);

        getContentPane().add(panelFacturalTotal);
        panelFacturalTotal.setBounds(30, 500, 450, 140);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Productos de Factura Total:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 264, 240, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Agrege productos a Factura Individual:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 464, 340, 30);

        tablaFacturaTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Costo"
            }
        ));
        panelFacturaIndividual.setViewportView(tablaFacturaTotal);

        getContentPane().add(panelFacturaIndividual);
        panelFacturaIndividual.setBounds(30, 290, 450, 140);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo menu.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 510, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //metodo para guardardatos
        //tablaFacturaIndividual.getRowCount()!=0 && tablaFacturaIndividual.getSelectedRow()!=-1
        System.out.println(tablaFacturaIndividual.getRowCount());
        if(tablaFacturaIndividual.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Debe agregar al menos un productos a la factura individual");
        }else{
            //guardarFacturaindividual
            numeroActual++;
            if(numeroActual<=numeroLimite){
                actualizarFacturaIndividual();
                //metodoGuardarFactura
                JOptionPane.showMessageDialog(null, "Factura Individual realizada");
            
            }else{
                JOptionPane.showMessageDialog(null, "Factuaras Divididas correctamente");
                this.dispose();
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void actualizarFacturaIndividual(){
        //txtIDFACT.setText();
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtNumFactDividida.setText(String.valueOf(numeroActual));
        hora();
        actualizarTablas();
    }
    public void actualizarTablas(){
        
    }
    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnAgregarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaDividida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaDividida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaDividida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaDividida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaDividida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboAnio;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane panelFacturaIndividual;
    private javax.swing.JScrollPane panelFacturalTotal;
    private javax.swing.JTable tablaFacturaIndividual;
    private javax.swing.JTable tablaFacturaTotal;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIDFACT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumFactDividida;
    // End of variables declaration//GEN-END:variables
}
