/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;

/**
 *
 * @author Christian
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public Administrador admin; 
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        admin = new Administrador();
        actualizarUser();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setSize(1000, 680);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    public void actualizarUser() {
        txtUser.setText(admin.conec.getLogin());
        txtPass.setText(admin.conec.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelServicio = new javax.swing.JPanel();
        btnBar = new javax.swing.JButton();
        btnMesa = new javax.swing.JButton();
        PanelCocina = new javax.swing.JPanel();
        btnOpcionCocina = new javax.swing.JButton();
        PanelCajero = new javax.swing.JPanel();
        btnOpcionCajero = new javax.swing.JButton();
        PanelAdmin = new javax.swing.JPanel();
        btnMasVendidos = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tablet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cargo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 590, 40, 10);

        txtUser.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtUser.setEnabled(false);
        getContentPane().add(txtUser);
        txtUser.setBounds(750, 530, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 560, 55, 10);

        txtPass.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtPass.setEnabled(false);
        getContentPane().add(txtPass);
        txtPass.setBounds(750, 560, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("User:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 530, 40, 10);

        txtCargo.setEnabled(false);
        getContentPane().add(txtCargo);
        txtCargo.setBounds(750, 590, 130, 20);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(680, 500, 220, 130);

        PanelServicio.setBackground(new java.awt.Color(253, 237, 216));
        PanelServicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elija tipo de servicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnBar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconoBar.png"))); // NOI18N
        btnBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btnBar.setContentAreaFilled(false);
        btnBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconoBar2.png"))); // NOI18N
        btnBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarActionPerformed(evt);
            }
        });

        btnMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconoMesa.png"))); // NOI18N
        btnMesa.setText("Mesa (Activar Mesa)");
        btnMesa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btnMesa.setContentAreaFilled(false);
        btnMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMesa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconoMesa2.png"))); // NOI18N
        btnMesa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelServicioLayout = new javax.swing.GroupLayout(PanelServicio);
        PanelServicio.setLayout(PanelServicioLayout);
        PanelServicioLayout.setHorizontalGroup(
            PanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServicioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelServicioLayout.setVerticalGroup(
            PanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelServicioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(PanelServicio);
        PanelServicio.setBounds(120, 120, 400, 160);

        PanelCocina.setBackground(new java.awt.Color(253, 237, 216));
        PanelCocina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cocina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnOpcionCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonPedido.png"))); // NOI18N
        btnOpcionCocina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btnOpcionCocina.setContentAreaFilled(false);
        btnOpcionCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionCocina.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonPedidoSelec.png"))); // NOI18N
        btnOpcionCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionCocinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCocinaLayout = new javax.swing.GroupLayout(PanelCocina);
        PanelCocina.setLayout(PanelCocinaLayout);
        PanelCocinaLayout.setHorizontalGroup(
            PanelCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpcionCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PanelCocinaLayout.setVerticalGroup(
            PanelCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpcionCocina, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PanelCocina);
        PanelCocina.setBounds(540, 120, 210, 160);

        PanelCajero.setBackground(new java.awt.Color(253, 237, 216));
        PanelCajero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cajero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnOpcionCajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonFact.png"))); // NOI18N
        btnOpcionCajero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btnOpcionCajero.setContentAreaFilled(false);
        btnOpcionCajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionCajero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonFactSelec.png"))); // NOI18N
        btnOpcionCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionCajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCajeroLayout = new javax.swing.GroupLayout(PanelCajero);
        PanelCajero.setLayout(PanelCajeroLayout);
        PanelCajeroLayout.setHorizontalGroup(
            PanelCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCajeroLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnOpcionCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelCajeroLayout.setVerticalGroup(
            PanelCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpcionCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCajero);
        PanelCajero.setBounds(290, 310, 230, 170);

        PanelAdmin.setBackground(new java.awt.Color(253, 237, 216));
        PanelAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administracion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnMasVendidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMasVendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/masVendidos.png"))); // NOI18N
        btnMasVendidos.setText("ProductosMas Vendidos");
        btnMasVendidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btnMasVendidos.setContentAreaFilled(false);
        btnMasVendidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasVendidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/masVendidosSelect.png"))); // NOI18N
        btnMasVendidos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMasVendidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasVendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminLayout = new javax.swing.GroupLayout(PanelAdmin);
        PanelAdmin.setLayout(PanelAdminLayout);
        PanelAdminLayout.setHorizontalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMasVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelAdminLayout.setVerticalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMasVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PanelAdmin);
        PanelAdmin.setBounds(540, 310, 210, 170);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo menu principal.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(100, 100, 800, 410);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartelrESTbAR.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 30, 320, 60);

        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 20, 420, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cubiertos.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 30, 60, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo menu.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 20, 800, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconoMenu.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 520, 160, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo menu.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 510, 800, 120);

        tablet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ipad2.png"))); // NOI18N
        getContentPane().add(tablet);
        tablet.setBounds(0, 0, 1010, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesaActionPerformed
        // TODO add your handling code here:
        PedidoMesa ventana = new PedidoMesa();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMesaActionPerformed

    private void btnBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarActionPerformed
        // TODO add your handling code here:
        PedidoBar ventana = new PedidoBar();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnBarActionPerformed

    private void btnOpcionCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCajeroActionPerformed
        // TODO add your handling code here:
        CajaPedido ventana = new CajaPedido();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnOpcionCajeroActionPerformed

    private void btnOpcionCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCocinaActionPerformed
        // TODO add your handling code here:
        PedidosCocina ventana = new PedidosCocina();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnOpcionCocinaActionPerformed

    private void btnMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasVendidosActionPerformed
        // TODO add your handling code here:
        ProdMasVendidos ventana = new ProdMasVendidos();
        ventana.setVisible(true);
                
    }//GEN-LAST:event_btnMasVendidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelCajero;
    private javax.swing.JPanel PanelCocina;
    private javax.swing.JPanel PanelServicio;
    private javax.swing.JButton btnBar;
    private javax.swing.JButton btnMasVendidos;
    private javax.swing.JButton btnMesa;
    private javax.swing.JButton btnOpcionCajero;
    private javax.swing.JButton btnOpcionCocina;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tablet;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
