/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Christian
 */
public class PedidoMesa extends javax.swing.JFrame {

    /**
     * Creates new form PedidoMesa
     */
    public PedidoMesa() {
        initComponents();
        //this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setSize(615, 791);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregarProd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnEliminarProd = new javax.swing.JButton();
        btnAgregarPed = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione lo productos que desea y anadalos.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 140, 340, 50);

        btnSalir2.setText("jButton1");
        btnSalir2.setContentAreaFilled(false);
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir2);
        btnSalir2.setBounds(260, 710, 80, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Producto", "Valor Producto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 240, 480, 130);

        btnAgregarProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/abajo.png"))); // NOI18N
        btnAgregarProd.setText("Agregar");
        btnAgregarProd.setContentAreaFilled(false);
        btnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProd.setFocusCycleRoot(true);
        btnAgregarProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarProd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/abajo2.png"))); // NOI18N
        btnAgregarProd.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProd);
        btnAgregarProd.setBounds(260, 400, 100, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cantidad de Producto seleccioando: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 380, 230, 14);

        jComboBox1.setBackground(new java.awt.Color(255, 204, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(350, 380, 90, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Costo", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 470, 470, 130);

        btnEliminarProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton.PNG"))); // NOI18N
        btnEliminarProd.setText("Vaciar Pedido");
        btnEliminarProd.setContentAreaFilled(false);
        btnEliminarProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarProd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonSelect.PNG"))); // NOI18N
        btnEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarProd);
        btnEliminarProd.setBounds(140, 630, 180, 40);

        btnAgregarPed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarPed.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton.PNG"))); // NOI18N
        btnAgregarPed.setText("Agregar Pedido");
        btnAgregarPed.setContentAreaFilled(false);
        btnAgregarPed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarPed.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonSelect.PNG"))); // NOI18N
        btnAgregarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPed);
        btnAgregarPed.setBounds(310, 630, 180, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icono restaurante.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 100, 160, 110);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("PEDIDO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 450, 120, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("MENU:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 220, 120, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo menu.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 550, 610);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ipad1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-10, 0, 620, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProdActionPerformed

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void btnAgregarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedActionPerformed
        // TODO add your handling code here:
        ConfirmarPedido ventana = new ConfirmarPedido(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAgregarPedActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPed;
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
